In [10]:
import numpy as np

def func(a, b):
    s=0
    n=len(a)
    x=np.zeros(3)
    for k in range(n-1, -1, -1):
        s=0
        for j in range(k+1, n, 1):
            s=s+a[k][j]*x[j]
        x[k]=(b[k]-s)/a[k][k]            
    
    
    return x
            

    
a=np.array([[3, 2, 4], [0, 1/3, 2/3], [0, 0, -8]])
b=np.array([1, 5/3, 0])
print(func(a, b))


[-3.  5. -0.]


In [13]:
import numpy as np

def func2(a, b):
    n=len(a)

    for k in range (0, n-1, 1):
        for i in range (k+1, n, 1):
            m=a[i][k]/a[k][k]
            a[i][k]=0
            for j in range (k+1, n, 1):
              a[i][j]=a[i][j]-(m*a[k][j])
              b[i]=b[i]-m*b[k]
    
    return a1, b1
                
a1=np.array([[2, 1, -3], [-1, 3, 2], [3, 1, -3]])
b1=np.array([-1, 12, 0])
print('Matriz:\n', a1)
a1, b1=func2(a1, b1)
print('Tranformação em Triangular Superior:\n', a1)
print('Solucao: ', func(a1,b1))
        

Matriz:
 [[ 2  1 -3]
 [-1  3  2]
 [ 3  1 -3]]
Tranformação em Triangular Superior:
 [[ 2  1 -3]
 [ 0  3  0]
 [ 0  0  1]]
Solucao:  [0.83333333 3.33333333 2.        ]
